# Generated by Django 5.2 on 2025-09-10 18:34

import django.contrib.postgres.fields
import django.db.models.deletion
import v1.property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to=v1.property.models.create_image_path)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('lga', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('benefits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, size=None)),
                ('type', models.CharField(max_length=50)),
                ('offer', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('tags', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to=v1.property.models.create_extra_media_path)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_media', to='property.property')),
            ],
        ),
    ]
