# Generated by Django 5.2 on 2025-08-28 19:19

import v1.property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to=v1.property.models.create_image_path)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
