# Generated by Django 5.2 on 2025-09-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='area',
            new_name='lga',
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default='test title', max_length=100),
            preserve_default=False,
        ),
    ]
