# Generated by Django 5.2.6 on 2025-09-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_description_alter_property_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
